name: Java build CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile Consumer
        run: mvn -B -U compile -f consumer/pom.xml
      - name: Compile Provider
        run: mvn -B -U compile -f provider/pom.xml
      - name: Test Consumer
        run: mvn -B -U test verify -f consumer/pom.xml
      - name: Test Provider
        run: mvn -B -U test verify -f provider/pom.xml
